# Basic
title: HengYk Blog
subtitle: 个人站
description: 具有浪漫主义情调的理想主义务实青年
# 头像里面的标题
avatarTitle: HengYk
# 头像里面的描述
avatarDesc: Java
url: "https://hengyk.github.io/"

# Comment
comment:
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 5366874726
    github: HengYk
    # twitter:
    mail: 18435138216@163.com

# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: 6df0775b62f76f59ce65d589692cd209

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3
#     host: auto


# 《----------------- 上面的信息修改成你自己的 ---------------------------》

# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于我, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
